### ISSUE TITLE
How to trigger an event from javascript (within controller/directive)

### ISSUE THREAD

**Issue by syrys** [mooyoul/angulartics-facebook-pixel#10]
Hi there,

Trying to figure out how this actually works from within a controller. There is no documentation on this as far as i can see.

Im wanting to pretty much trigger some Events from within my controller (when user does X, Y, Z action), the controller needs to trigger a `ViewContent` or `Lead` event. How would i go about doing this?

Cheers.

**Comment by syrys** [comment]
Just to add

ofcorse from within the controller i could add something like this:

```
if (window.fbq) {
    fbq('track', 'Lead', 'blah');
}
```

But is this the way it should be done?

**Comment by lazychino** [comment]
@syrys  you should use angulartics service `$analytics` mentioned [here](http://angulartics.github.io/) on the section **Using the API**

**Comment by syrys** [comment]
@lazychino 
Seems like if you have google analytics and FB both attached, and both corresponding modules/libs of angulartics attached, an event triggered by using `$analyitics` would trigger on both. In a sense its handy, but on the other hand, maybe there should be some special methods to trigger the event only on 1 provider and not the other(s). And from a quick glance, there seems to be none, other than just calling the provider directly as i have mentioned on my earlier response.

Ah well, not really sure what the right way is, but for now, i think the direct provider approach is working without any issue for me.

**Comment by mooyoul** [comment]
Yeah, that's due to implementation of angulartics core. You can't send event to **specific** provider.
