### ISSUE TITLE
Can we use this to track conversions/registrations?

### ISSUE THREAD

**Issue by niyando** [mooyoul/angulartics-facebook-pixel#2]
Good work on the pageviews. Does it support tracking registrations and conversions?

**Comment by mooyoul** [comment]
Hi @niyando,
Sorry for late reply.
I'm working on supporting event tracking (like page conversions) in angulartics-facebook-pixel.
It will be released on v0.2.0

**Comment by erikverheij** [comment]
That would be very nice!

**Comment by mooyoul** [comment]
Woo. this is now supported feature by PR #5  :)
Please install 0.2.0, and enjoy tracking your own events 🎉
