### ISSUE TITLE
Hash issue

### ISSUE THREAD

**Issue by juanmarinballastlane** [mooyoul/angulartics-facebook-pixel#3]
When my app has disabled the $locationProvider.html5Mode(true); the URLs tracking are only for my base URL (localhost), only when the html5Mode is enabled, it works fine. I'm doing something wrong?

**Comment by mooyoul** [comment]
There are known issues about disabling `$locationProvider.html5Mode(true)` on Angulartics.
See: https://github.com/angulartics/angulartics/issues?utf8=%E2%9C%93&q=is%3Aissue+html5mode

Anyway, I'm going to resolve this issue. I'll update details. Thanks!

**Comment by yaronguez** [comment]
I'm not calling $locationProvider.html5mode(true) anywhere in my code but the page views are tracking my base URL only. Looking at the net panel in Firebug shows that a hash is included in every page view event. Do I need to do something to keep the hash from being sent to Facebook so that the page view event is treated as a separate page? This works perfectly with Google Analytics.

**Comment by mooyoul** [comment]
Hi @yaronguez ! Are you using `angulatics-google-analytics` package to track your visitors?

**Comment by yaronguez** [comment]
Hi @mooyoul ! Yes I'm using `angulartics-google-analytics` package to track my visitors and every page view shows up as domain.com/state not domain.com/#/state in GA.

**Comment by mooyoul** [comment]
@yaronguez Could you check `angulartics-google-analytics` version which you are using?

**Comment by yaronguez** [comment]
Version 0.1.1.  Just to clarify, the Google Analytics tracking is working as expected.

**Comment by mooyoul** [comment]
@yaronguez Yup, I understand what you mean. 
I just want to know how `angulartics-google-analytics` which you are using handles hash url. don't worry :)

I'll release next version on today~tomorrow which is fixed this issue. :bow:

**Comment by yaronguez** [comment]
Thanks so much! Keep up the good work :-)

**Comment by mooyoul** [comment]
Hmm. I'm in trouble with Facebook Pixel tracking script.
Facebook Pixel tracking script was changed on Apr 05. and something changed.

When sending 'PageView' pixel to facebook, Pixel tracking script reads PageView url from `location.href`. (See below screenshot)

<img width="911" alt="2016-04-05 7 26 52" src="https://cloud.githubusercontent.com/assets/2101743/14265975/d27ac24a-faff-11e5-9413-e5a39b2b749a.png">

That's hard-coded, isolated scope. and cannot access from `window.fbq` object.

so, i'm considering tracking script modification to control PageView url. and ship it in package.
it may resolve issue. but that modified script is not official. it may cause unexpected behavior. (e.g. out-of-date tracking script version.) I'm worrying about that.

What do you think about solution? or Any ideas? @yaronguez  @juankmarin

**Comment by yaronguez** [comment]
I just switched to $locationProvider.html5Mode(true); so that my URLs no longer have the # hash. This solves my problem and makes for a nicer user experience anyway. I'd avoid modifying the official FB tracking script. I'm not sure how else to get around that :-/

**Comment by mooyoul** [comment]
Facebook Pixel script now supports hash locations.
They reads pageview url from `location.href` which included hash :)

so I'm closing this issue. thanks!
