### ISSUE TITLE
Pixel page track

### ISSUE THREAD

**Issue by simonkontschak** [mooyoul/angulartics-facebook-pixel#7]
Hi, 

if i understand correctly, the `$analyticsProvider.registerpageTrack` is not necessary, cause the facebook-pixel is tracking route changes itself and tracks PageViews automatically?

How can i disable the page-view tracking in this case?
Let's say i just want to use the event tracking.

**Comment by mooyoul** [comment]
Yup, that's correct. Pixel automatically tracks route changes itself.

You can turn off this feature and track only events. 
Just add `fbq.disablePushState = true;` into your pixel snippet.

Like this:

``` html
    <script type="text/javascript">
        !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
                n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
            n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
                document,'script','//connect.facebook.net/en_US/fbevents.js');
        fbq.disablePushState = true; // ADD THIS LINE!
        fbq('init', 'YOUR_PIXEL_SCRIPT');
    </script>
```

Please note that Facebook Pixel will send initial PageView even turn off pushState tracking feature.
(Facebook Pixel Helper claims if there are no pixels)
